version: "3"
services:
  back: 
    image: node:14
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    volumes:
      - ./back:/opt/app:z
    command: 
      - /bin/bash
      - -c
      - | 
        cd /opt/app
        npm install
        sleep 15
        npx nodemon .
    networks:
      - accel
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment: 
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - accel
  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - accel
  dashboard_server:
    image: node:14
    volumes:
      - ./dashboard:/opt/app:z
    ports:
      - 5000:5000
    environment:
      - PORT=5000
    command: 
      - /bin/bash
      - -c
      - | 
        cd /opt/app
        npm install
        sleep 15
        npx nodemon ./server --ignore src
    networks:
      - accel
  consumer:
    image: node:14
    volumes:
      - ./consumer:/opt/app:z
    command: 
      - /bin/bash
      - -c
      - | 
        cd /opt/app
        npm install
        sleep 15
        npx nodemon .
    networks:
      - accel
  score:
    image: node:14
    volumes:
      - ./score:/opt/app:z
    command: 
      - /bin/bash
      - -c
      - | 
        cd /opt/app
        npm install
        sleep 15
        npx nodemon .
    networks:
      - accel
  # auth:
  #   image: node:14
  #   ports:
  #     - 3003:3003
  #   environment:
  #     - PORT=3003
  #     - ./auth:/opt/app:z
  #   command: 
  #     - /bin/bash
  #     - -c
  #     - | 
  #       cd /opt/app
  #       npm install
  #       npx nodemon .
  #   networks:
  #     - accel
networks:
  accel: